server:
  port: 8080

management:
  server:
    port: 8081

spring:
  application:
    name: fm-demo
  datasource:
    url: jdbc:mysql://localhost:3306/frame_me_test_2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ME(O30Gx4FH/kvKUyuawsrt4skU0l/YzE8S5XsezegH9V9gEq92XGCFTqR58+n3O6L1)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    dynamic:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 10
      datasource:
        second:
          url: jdbc:mysql://localhost:3306/frame_me_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: ME(O30Gx4FH/kvKUyuawsrt4skU0l/YzE8S5XsezegH9V9gEq92XGCFTqR58+n3O6L1)
          driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    clients:
      connect-timeout: 3s
      read-timeout: 10s
    serviceclient:
      tester:
        base-url: http://localhost:9090
        read-timeout: 5s
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id

logging:
  file:
    path: ./logs
    name: ${spring.application.name}

springdoc:
  # /v3/api-docs
  api-docs:
    enabled: true
  # /swagger-ui.html
  swagger-ui:
    enabled: true

# 依赖通过 Maven profile "p6spy" 引入：mvn ... -Pp6spy
decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true

me:
  #  snowflake:
  #    worker-id: 2
  #    datacenter-id: 2
  mybatis:
    meta-object-handler:
      enabled: true
    snowflake:
      worker-id: 1
      datacenter-id: 1
  swagger:
    enabled: true
    title: FM Demo API
    description: FM Demo 接口文档
    version: 1.0.0
    groups:
      - name: demo-api
        paths-to-match:
          - /api/**
